#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

SERVICE_NAME="campus-login"
SCRIPT="/usr/bin/campus-login.sh"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$SCRIPT"
    procd_set_param respawn 2000 5 5
    procd_close_instance
}

stop_service() {
    killall campus-login.sh 2>/dev/null
}
